select Name FROM students;
SELECT AGE FROM STUDENTS WHERE AGE > 30;
SELECT * FROM STUDENTS WHERE AGE='30' AND GENDER='F';
SELECT POINTS FROM STUDENTS WHERE NAME='Alex';
INSERT INTO STUDENTS(NAME, AGE, GENDER, POINTS) VALUES ('JANA', '20', 'F', '600');
UPDATE STUDENTS SET POINTS=350 WHERE POINTS=300;
UPDATE STUDENTS SET POINTS=150 WHERE POINTS=200;

CREATE TABLE graduates (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    Age INT,
    Gender TEXT,
    Points INT,
	Graduation  TEXT );
INSERT INTO graduates (ID, Name, Age, Gender,Points)
 SELECT ID, Name, Age, Gender,Points FROM students WHERE Name="Layal";
 UPDATE graduates SET Graduation= "08/09/2018" WHERE Name="Layal";
 DELETE FROM students WHERE name ="Layal";