select Name FROM students;
SELECT AGE FROM STUDENTS WHERE AGE > 30;
SELECT * FROM STUDENTS WHERE AGE='30' AND GENDER='F';
SELECT POINTS FROM STUDENTS WHERE NAME='Alex';
INSERT INTO STUDENTS(NAME, AGE, GENDER, POINTS) VALUES ('JANA', '20', 'F', '600');
UPDATE STUDENTS SET POINTS=350 WHERE POINTS=300;
UPDATE STUDENTS SET POINTS=150 WHERE POINTS=200;